package com.hongru.parse;

import org.junit.Test;

/**
 * Created by chenhongyu on 2016/10/17.
 */
public class TestHTMLDateParse {

    @Test
    public void testParse() {
        String html = "";
        html += "";
        html += "";
        html += "<!DOCTYPE html>";
        html += "<!--[if lt IE 7]><html class=\"ie ie6 lt8 lt9\"><![endif]-->";
        html += "<!--[if IE 7]><html class=\"ie ie7 lt8 lt9\"><![endif]-->";
        html += "<!--[if IE 8]><html class=\"ie ie8 lt9\"><![endif]-->";
        html += "<!--[if IE 9]><html class=\"ie ie9\"><![endif]-->";
        html += "<!--[if (gt IE 9) | !(IE)]><!-->";
        html += "<html>";
        html += "<!--<![endif]-->";
        html += "<head>";
        html += "    <meta charset=\"utf-8\">";
        html += "";
        html += "<meta name=\"author\" content=\"hongru\" />";
        html += "";
        html += "<meta name=\"keywords\" content=\"爱儿美,新鸿儒,网站建设\" />";
        html += "";
        html += "<meta name=\"description\" content=\"新鸿儒\"/>";
        html += "";
        html += "<meta http-equiv=\"X-UA-Compatible\" content=\"chrome=1,IE=edge\" />";
        html += "";
        html += "<meta content=\"width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1\" name=\"viewport\" />";
        html += "";
        html += "<title>新鸿儒签约爱儿美  缔造中国儿童摄影王国_新闻_新鸿儒</title>";
        html += "";
        html += "<link rel=\"shortcut icon\" href=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/favicon.ico\" type=\"image/x-icon\" />";
        html += "";
        html += "<link rel=\"stylesheet\" href=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/css/common.css\">";
        html += "";
        html += "<script>if (/*@cc_on!@*/false && document.documentMode === 10) document.documentElement.className += ' ie10';</script>";
        html += "";
        html += "<script>if (/*@cc_on!@*/false && document.documentMode === 11) document.documentElement.className += ' ie11';</script>";
        html += "";
        html += "<!-- 添加IE10+Class -->";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/jquery.js\"></script>";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/velocity.min.js\"></script>";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/jquery.lazyload.js\"></script>";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/common.js\"></script>";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/autuimg.js\"></script>";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/swfobject.js\"></script>    ";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/statics/js/search.js\"></script> ";
        html += "";
        html += "<!--[if lt IE 9]>";
        html += "";
        html += "";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/html5.js\"></script>";
        html += "";
        html += "<script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/respond.src.js\"></script>";
        html += "";
        html += "<![endif]-->";
        html += "";
        html += "<!--公用文件-->";
        html += "";
        html += "<!-- ";
        html += "";
        html += "<script>";
        html += "";
        html += "    var _hmt = _hmt || [];";
        html += "";
        html += "    (function () {";
        html += "";
        html += "        var hm = document.createElement(\"script\");";
        html += "";
        html += "        hm.src = \"//hm.baidu.com/hm.js?58051a791d8f16fe5b946696e68cc488\";";
        html += "";
        html += "        var s = document.getElementsByTagName(\"script\")[0];";
        html += "";
        html += "        s.parentNode.insertBefore(hm, s);";
        html += "";
        html += "    })();";
        html += "";
        html += "</script>";
        html += "";
        html += "-->";
        html += "";
        html += "<script type=\"text/javascript\">";
        html += "";
        html += "var _bdhmProtocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");";
        html += "";
        html += "document.write(unescape(\"%3Cscript src='\" + _bdhmProtocol + \"hm.baidu.com/h.js%3F58051a791d8f16fe5b946696e68cc488' type='text/javascript'%3E%3C/script%3E\"));";
        html += "";
        html += "</script>";
        html += "";
        html += "";
        html += "";
        html += "<!--页面内引用文件-->";
        html += "";
        html += "";
        html += "    <script src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/js/news.js\"></script>";
        html += "</head>";
        html += "<body>";
        html += "    <div class=\"mousebox\"><i class=\"mouse\"></i></div>";
        html += "    <header class=\"header\">";
        html += "";
        html += "        <div class=\"wrap cf\">";
        html += "";
        html += "            <div class=\"logo\"><a href=\"/index.html\"><img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/logo.png\" alt=\"新鸿儒\" /></a></div>";
        html += "";
        html += "            <nav>";
        html += "";
        html += "                <ul class=\"cf\">";
        html += "";
        html += "                    <li ><a href=\"/index.html\">首页</a></li>";
        html += "";
        html += "                    <li><a href=\"/case/index.html\">客户案例</a></li>";
        html += "";
        html += "                    <li><a href=\"/service/index.html\">服务</a></li>";
        html += "";
        html += "                    <li><a href=\"/innovation/index.html\">创新</a></li>";
        html += "";
        html += "                    <li><a href=\"/company/index.html\">公司</a></li>";
        html += "                    <li class=\"n-news\"><a href=\"/news/index.html\">新闻</a></li>";
        html += "                    <li><a href=\"/job/index.html\">人才</a></li>";
        html += "";
        html += "                    <li><a href=\"/contact/index.html\">联系</a></li>";
        html += "";
        html += "                </ul>";
        html += "";
        html += "            </nav>";
        html += "";
        html += "            <div class=\"menu-right cf\">";
        html += "";
        html += "            	<div class=\"l\">";
        html += "";
        html += "                    <a href=\"#\" class=\"a0 on\">中文</a>";
        html += "";
        html += "                    <em>/</em>";
        html += "";
        html += "                    <a href=\"#\" class=\"a0\">EN</a>";
        html += "";
        html += "                </div>";
        html += "";
        html += "                <div class=\"r\">";
        html += "";
        html += "                	<div class=\"a2\" title=\"搜索\">";
        html += "                                        ";
        html += "";
        html += "                        <input type=\"text\" id=\"b_username\" placeholder=\"网站建设\" class=\"sear\" />";
        html += "";
        html += "                        <input type=\"button\" id=\"btnSearchHead\" class=\"but icon pic_21\" />";
        html += "";
        html += "                	</div>";
        html += "";
        html += "                    <a href=\"http://evi.hongru.com/\" target=\"_blank\" class=\"a3\" title=\"用户管理系统\"><i class=\"icon pic_22\"></i></a>";
        html += "";
        html += "                    <button class=\"menu_h\"><span>Menu</span></button>";
        html += "";
        html += "                </div>";
        html += "";
        html += "                ";
        html += "";
        html += "            </div>";
        html += "";
        html += "            <div class=\"top-r cf\">";
        html += "";
        html += "                <div class=\"b cf\"><i class=\"icon pic_1\"></i><i>我们的服务遍布中国</i></div>";
        html += "";
        html += "                <div class=\"fixd-box\">";
        html += "";
        html += "                    <div class=\"wrap cf\"><a href=\"javascript:;\" class=\"close\"></a>";
        html += "";
        html += "                        <h2>我们的服务遍布中国<br />乃至世界</h2>";
        html += "";
        html += "                        <div class=\"txt cf\">";
        html += "";
        html += "                            <div class=\"left\">";
        html += "";
        html += "                                <dl class=\"cf\">";
        html += "";
        html += "                                    <dt><img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/map_03.jpg\" /></dt>";
        html += "";
        html += "                                    <dd><span>新鸿儒所服务的品牌地域与城市</span><br />";
        html += "";
        html += "                                        <span>北京</span>";
        html += "";
        html += "                                        <span>天津</span>";
        html += "";
        html += "                                        <span>上海</span>";
        html += "";
        html += "                                        <span>广州</span>";
        html += "";
        html += "                                        <span>深圳</span>";
        html += "";
        html += "                                        <span>香港</span>";
        html += "";
        html += "                                        <span>厦门</span>";
        html += "";
        html += "                                        <span>江苏</span>";
        html += "";
        html += "                                        <span>浙江</span>";
        html += "";
        html += "                                        <span>山东</span>";
        html += "";
        html += "                                        <br />";
        html += "";
        html += "                                        <span>重庆</span>";
        html += "";
        html += "                                        <span>长沙</span>";
        html += "";
        html += "                                        <span>武汉</span>";
        html += "";
        html += "                                        <span>成都</span>";
        html += "";
        html += "                                        <span>西安</span>";
        html += "";
        html += "                                        <span>宁夏</span>";
        html += "";
        html += "                                        <span>丽江</span>";
        html += "";
        html += "                                        <span>青海</span>";
        html += "";
        html += "                                        <span>云南</span>";
        html += "";
        html += "                                        <span>乌鲁木齐</span>";
        html += "";
        html += "                                        <br />";
        html += "";
        html += "                                        <span>黑龙江</span>";
        html += "";
        html += "                                        <span>内蒙古</span>";
        html += "";
        html += "                                        <span>河北</span>";
        html += "";
        html += "                                        <span> ...</span>";
        html += "";
        html += "                                        ";
        html += "";
        html += "                                     </dd>";
        html += "";
        html += "                                </dl>";
        html += "";
        html += "                                <dl class=\"cf\">";
        html += "";
        html += "                                    <dt><img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/map_06.jpg\" /></dt>";
        html += "";
        html += "                                    <dd><span>新鸿儒服务与合作的全球各地</span><br />";
        html += "";
        html += "                                        <span>美国</span>";
        html += "";
        html += "                                        <span>加拿大</span>";
        html += "";
        html += "                                        <span>德国</span>";
        html += "";
        html += "                                        <span>法国</span>";
        html += "";
        html += "                                        <span>英国</span>";
        html += "";
        html += "                                        <span>瑞士</span>";
        html += "";
        html += "                                        <span>意大利</span>";
        html += "";
        html += "                                        <span>荷兰</span>";
        html += "";
        html += "                                        <br />";
        html += "";
        html += "                                        <span>印度</span>";
        html += "";
        html += "                                        <span>日本 </span>";
        html += "";
        html += "                                        <span>韩国</span>";
        html += "";
        html += "                                        <span> ...</span>";
        html += "";
        html += "                                     </dd>";
        html += "";
        html += "                                </dl>";
        html += "";
        html += "                            </div>";
        html += "";
        html += "                            <div class=\"right\">";
        html += "";
        html += "                                <p>";
        html += "";
        html += "                               不论你的品牌在何处<br />";
        html += "";
        html += "我们都可以提供完善的服务与帮助";
        html += "";
        html += "                                </p>";
        html += "";
        html += "                                 <p>";
        html += "";
        html += "                                致电<br />                                ";
        html += "";
        html += "                                     </p>";
        html += "";
        html += "                                 <span>010-5126 7718</span>";
        html += "";
        html += "                            </div>";
        html += "";
        html += "                        </div>";
        html += "";
        html += "                    </div>";
        html += "";
        html += "                </div>";
        html += "";
        html += "            </div>";
        html += "";
        html += "        </div>";
        html += "";
        html += "    </header>";
        html += "    <section class=\"main\">";
        html += "        ";
        html += "        <div class=\"news-detail wrap\">";
        html += "           ";
        html += "            <div class=\"contents cf\">";
        html += "                <div class=\"new_right\">";
        html += "                    <div class=\"rblock\">";
        html += "                        <div class=\"rblock_tit\">人气排行</div>";
        html += "                        <div class=\"rblock_con\">";
        html += "                        	                            <ul>";
        html += "                                <li><span class=\"an\">1</span><a target=\"_blank\" title=\"猴子请来的救兵——新鸿儒\" href=\"/content/details_6_3511.html\">猴子请来的救兵——新鸿儒</a></li><li><span class=\"an\">2</span><a target=\"_blank\" title=\"新鸿儒助力SOHO3Q项目成功上线\" href=\"/content/details_6_2600.html\">新鸿儒助力SOHO3Q项目成功上线</a></li><li><span class=\"an\">3</span><a target=\"_blank\" title=\"2016年，新鸿儒大不一样\" href=\"/content/details_6_3472.html\">2016年，新鸿儒大不一样</a></li><li><span class=\"an\">4</span><a target=\"_blank\" title=\"潘石屹“恭喜新鸿儒“ SOHO 3Q即将启动 \" href=\"/content/details_6_2561.html\">潘石屹“恭喜新鸿儒“ SOHO 3Q即将启动 </a></li><li><span class=\"an\">5</span><a target=\"_blank\" title=\"新鸿儒倾力打造蒂森克虏伯集团子品牌官网\" href=\"/content/details_6_3055.html\">新鸿儒倾力打造蒂森克虏伯集团子品牌官网</a></li><li><span class=\"an\">6</span><a target=\"_blank\" title=\"新鸿儒HTML5花样拜大年20万用户捧场闹新春\" href=\"/content/details_6_2608.html\">新鸿儒HTML5花样拜大年20万用户捧场闹新春</a></li><li><span class=\"an\">7</span><a target=\"_blank\" title=\"新鸿儒新年奏响骏马集团互联网布局第一章\" href=\"/content/details_6_2593.html\">新鸿儒新年奏响骏马集团互联网布局第一章</a></li><li><span class=\"an\">8</span><a target=\"_blank\" title=\"在下一个路口相遇——新鸿儒《遇见真实的你》有奖调查\" href=\"/content/details_6_2560.html\">在下一个路口相遇——新鸿儒《遇见真实的你》有奖调查</a></li><li><span class=\"an\">9</span><a target=\"_blank\" title=\"意尔康官网倾情上线揭开品牌的秘密\" href=\"/content/details_6_2558.html\">意尔康官网倾情上线揭开品牌的秘密</a></li><li><span class=\"an\">10</span><a target=\"_blank\" title=\"北京公交集团官网新版亮相智慧亲民2015\" href=\"/content/details_6_2594.html\">北京公交集团官网新版亮相智慧亲民2015</a></li>                            </ul>";
        html += "";
        html += "                        </div>";
        html += "                    </div>";
        html += "                </div>";
        html += "";
        html += "                <div class=\"new_left\">";
        html += "                    <div class=\"location\">";
        html += "                        <div class=\"site\">当前位置：<a href='/'  class=\"home\"  title=\"首页\">首页</a>&gt;<a  href=/news/index.html title=新闻>新闻</a>&gt;<span >正文</span></div>";
        html += "                    </div>";
        html += "                    <!--startprint-->";
        html += "                    <div class=\"article\">";
        html += "                        <h2>新鸿儒签约爱儿美  缔造中国儿童摄影王国</h2>";
        html += "                        <h3><span>发布时间：：2016-01-28</span><span id=\"hitid\">浏览：290</span><span class=\"print\"><a onclick=\"doPrint()\">打印</a></span><span class=\"news_info\">字号：<a  id=\"big\">大</a><a id=\"medium\" class=\"on\" >中</a><a id=\"small\">小</a></span></h3>";
        html += "";
        html += "                        ";
        html += "                        <div class=\"edit_con_original\">　　日前，新鸿儒正式签约爱儿美儿童摄影，为其塑造全新响应式官网。<br />";
        html += "";
        html += "<br />";
        html += "";
        html += "　　爱儿美儿童摄影本着“爱由心生、因爱而美”的经营理念，历经十多年的发展，目前已形成11家北京直营店，数百家全国加盟店、拥有超过100万名会员的儿童摄影连锁机构。<br />";
        html += "";
        html += "<br />";
        html += "";
        html += "　　作为具有特色的老牌儿童摄影中心，爱儿美以优质的服务和良好的体验赢得用户良好的品牌口碑，并希望借以互联网和移动互联网的优势，吸引更多用户关注。<br />";
        html += "";
        html += "<br />";
        html += "";
        html += "　　新鸿儒团队将深入了解爱儿美儿童摄影的行业属性与品牌特性，洞察用户需求，了解用户的浏览及审美习惯，从而为爱儿美打造以用户体验为核心的互联网视觉形象。<br />";
        html += "";
        html += "　　<br />";
        html += "";
        html += "　　新官网将采用HTML5最新技术，实现页面的响应式布局——随着屏幕大小的改变，页面将自动适应屏幕尺寸，从而满足移动端用户的浏览，实现品牌的跨屏幕传播。 <br />";
        html += "";
        html += "<br />";
        html += "";
        html += "　　期待新鸿儒与爱儿美的合作，能够为其带来更多的用户与价值。 <br /></div>                        ";
        html += "                        ";
        html += "                    </div>";
        html += "                    <!--endprint-->";
        html += "                    <div class=\"news-share\">";
        html += "                            <div class=\"share\">";
        html += "                                <div class=\"box\">";
        html += "                                    <span class=\"t\">分享新鸿儒 分享未来 · </span>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_14\" data-qrcode=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/11.png\" title=\"微信\"></a>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_15\" data-qrcode=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/11.png\" title=\"朋友圈\"></a>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_16\" data-txt=\"新鸿儒\" title=\"微博\"></a>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_17\" data-txt=\"新鸿儒\" title=\"QQ\"></a>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_18\" data-txt=\"新鸿儒\" title=\"Facebook\"></a>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_19\" data-txt=\"新鸿儒\" title=\"Twitter\"></a>";
        html += "                                    <a href=\"javascript:;\" class=\"icon pic_20\" data-txt=\"新鸿儒\" title=\"Google+\"></a>";
        html += "                                </div>";
        html += "                            </div>";
        html += "                        </div>";
        html += "";
        html += "                    <div class=\"fp\">";
        html += "                    ";
        html += "                     <span>上一篇：<a title=\"亚威股份携手新鸿儒  “机床第一股”走向互联网\" href=\"/content/details_6_3584.html\">亚威股份携手新鸿儒  “机床第一股”走向互联网</a></span>";
        html += "                        <span>下一篇：<a title=\"猴子请来的救兵——新鸿儒\" href=\"/content/details_6_3511.html\">猴子请来的救兵——新鸿儒</a></span>";
        html += "                        <a class=\"close\" title=\"关闭窗口\" href=\"javascript:window.close();\">[关闭窗口]</a></div>";
        html += "                    </div>";
        html += "                ";
        html += "";
        html += "            </div>";
        html += "";
        html += "        </div>";
        html += "";
        html += "    </section>";
        html += "    ";
        html += "    <footer class=\"footer\">";
        html += "";
        html += "";
        html += "";
        html += "        <div class=\"wrap cf\">";
        html += "";
        html += "";
        html += "";
        html += "                <div class=\"left\">";
        html += "";
        html += "";
        html += "";
        html += "                        <ul class=\"cf\">";
        html += "";
        html += "";
        html += "";
        html += "                                <li>";
        html += "";
        html += "";
        html += "";
        html += "                                        <h2><a href=\"/case/index.html\">客户与案例</a></h2>";
        html += "";
        html += "";
        html += "";
        html += "                                        <span><a href=\"/case/index.html\">客户案例</a></span> ";
        html += "";
        html += "";
        html += "";
        html += "                                        <!--<span><a href=\"#\">我要建站</a></span>--> ";
        html += "";
        html += "";
        html += "";
        html += "                                </li>";
        html += "";
        html += "";
        html += "";
        html += "                                <li>";
        html += "";
        html += "";
        html += "";
        html += "                                        <h2><a href=\"/service/index.html\">服务</a></h2>";
        html += "";
        html += "";
        html += "";
        html += "                                        <span><a href=\"/service/website.html\">网站建设</a></span> <span><a href=\"/service/mobile.html\">移动应用</a></span> <span><a href=\"/service/EOMS.html\">互联网运维</a></span> <span><a href=\"/service/video.html\">影像创意</a></span> </li>";
        html += "";
        html += "";
        html += "";
        html += "                                <li>";
        html += "";
        html += "";
        html += "";
        html += "                                        <h2><a href=\"/innovation/index.html\">创新</a></h2>";
        html += "";
        html += "";
        html += "";
        html += "                                        <span><a href=\"/innovation/PM.html\">产品规范化</a></span> <span><a href=\"/innovation/IE.html\">交互应用</a></span> <span><a href=\"/innovation/SH.html\">移动用户系统</a></span> <span><a href=\"/innovation/WI.html\">WI/WV体系</a></span> ";
        html += "";
        html += "";
        html += "";
        html += "                                        <!--<span><a href=\"/contact/story.html\">我要创新</a></span>--> ";
        html += "";
        html += "";
        html += "";
        html += "                                </li>";
        html += "";
        html += "";
        html += "";
        html += "                                <li>";
        html += "";
        html += "";
        html += "";
        html += "                                        <h2><a href=\"/company/index.html\">公司</a></h2>";
        html += "";
        html += "";
        html += "";
        html += "                                        <span><a href=\"/company/index.html\">关于我们</a></span> <span><a href=\"/company/index.html#course\">发展历程</a></span> <span><a href=\"/job/index.html\">人才</a></span> <span><a href=\"/news/index.html\">公司新闻</a></span> <span><a href=\"/contact/index.html\">联系</a></span> </li>";
        html += "";
        html += "";
        html += "";
        html += "                                <li>";
        html += "";
        html += "";
        html += "";
        html += "                                        <h2><a href=\"/help/index.html\">帮助中心</a></h2>";
        html += "";
        html += "";
        html += "";
        html += "                                        <span><a href=\"/help/index.html\">用户帮助</a></span> <span><a href=\"http://evi.hongru.com/\" target=\"_blank\">项目监控</a></span> <span><a href=\"http://idc.xinhongru.com/index.asp\" target=\"_blank\">鸿主机</a></span> </li>";
        html += "";
        html += "";
        html += "";
        html += "                        </ul>";
        html += "";
        html += "";
        html += "";
        html += "                </div>";
        html += "";
        html += "";
        html += "";
        html += "                <div class=\"right\">";
        html += "";
        html += "";
        html += "";
        html += "                        <div class=\"foot-logo\"><img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/upload/2.png\" /></div>";
        html += "";
        html += "";
        html += "";
        html += "                        <div class=\"tit\"> <span>Copyright 1998－2016 hongru.com</span> <span>版权所有 北京新鸿儒世纪网络技术有限公司</span><br/><span><a target=\"_blank\" href=\"http://www.miibeian.gov.cn/\">京ICP备09021176号</a>    公安机关备案号：11010502030953</span></div>";
        html += "";
        html += "";
        html += "";
        html += "                        <div class=\"QR\">";
        html += "";
        html += "";
        html += "";
        html += "                                 <img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/upload/9.png\" /> <img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/upload/10.png\" />";
        html += "";
        html += "";
        html += "";
        html += "                        </div>";
        html += "";
        html += "";
        html += "";
        html += "                        <div class=\"ph\"> <i class=\"icon\"></i>";
        html += "";
        html += "";
        html += "";
        html += "                                <p> <span><i>010-51267718</i>　<i>59283042</i></span> </p>";
        html += "";
        html += "";
        html += "";
        html += "                        </div>";
        html += "";
        html += "";
        html += "";
        html += "                </div>";
        html += "";
        html += "";
        html += "";
        html += "        </div>";
        html += "";
        html += "";
        html += "";
        html += "</footer>";
        html += "";
        html += "";
        html += "";
        html += "<div class=\"dingwei\" style=\"display:none;\"> <div class=\"site\">当前位置：<a href='/'  class=\"home\"  title=\"首页\">首页</a>&gt;<a  href=/news/index.html title=新闻>新闻</a>&gt;<span >正文</span></div> </div>";
        html += "";
        html += "";
        html += "";
        html += "<script>";
        html += "";
        html += "";
        html += "";
        html += "	//导航定位   ";
        html += "";
        html += "";
        html += "";
        html += "    $(function () {";
        html += "";
        html += "";
        html += "";
        html += "        var Menu = $.trim($(\"div.dingwei>div.site>a:eq(0)\").next().text());";
        html += "";
        html += "";
        html += "";
        html += "        $(\"nav>ul.cf>li>a\").map(function () {";
        html += "";
        html += "";
        html += "";
        html += "            if ($.trim($(this).text()) == Menu) {";
        html += "";
        html += "";
        html += "";
        html += "                $(this).parent().addClass(\"on\").siblings().removeClass('on');";
        html += "";
        html += "";
        html += "";
        html += "            }";
        html += "";
        html += "";
        html += "";
        html += "            var Menu1 = $.trim($(\"div.dingwei>div.site>a:eq(0)\").next().next().text());";
        html += "";
        html += "";
        html += "";
        html += "            $(\"nav>ul.cf>li>a\").map(function () {";
        html += "";
        html += "";
        html += "";
        html += "                if ($.trim($(this).text()) == Menu1) {";
        html += "";
        html += "";
        html += "";
        html += "                    $(this).parent().addClass(\"on\").siblings().removeClass('on');";
        html += "";
        html += "";
        html += "";
        html += "                }";
        html += "";
        html += "";
        html += "";
        html += "            })";
        html += "";
        html += "";
        html += "";
        html += "        })";
        html += "";
        html += "";
        html += "";
        html += "    });";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "	</script> ";
        html += "";
        html += "";
        html += "";
        html += "<script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id='cnzz_stat_icon_1256947233'%3E%3C/span%3E%3Cscript src='\" + cnzz_protocol + \"s11.cnzz.com/z_stat.php%3Fid%3D1256947233' type='text/javascript'%3E%3C/script%3E\"));</script> ";
        html += "";
        html += "";
        html += "";
        html += "<script language=\"javascript\" type=\"text/javascript\" src=\"http://js.users.51.la/18692024.js\"></script>";
        html += "";
        html += "";
        html += "";
        html += "<noscript>";
        html += "";
        html += "";
        html += "";
        html += "<a href=\"http://www.51.la/?18692024\" target=\"_blank\"><img alt=\"我要啦免费统计\" src=\"http://img.users.51.la/18692024.asp\" style=\"border:none\" /></a>";
        html += "";
        html += "";
        html += "";
        html += "</noscript>";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "<div class=\"hr_index_light\">";
        html += "";
        html += "";
        html += "";
        html += "	<h4><a href=\"javascript:void(0)\"></a>重要的事情，电话里聊</h4>";
        html += "";
        html += "";
        html += "";
        html += "    <div class=\"hr_index_part1 fixed\">";
        html += "";
        html += "";
        html += "";
        html += "    <div class=\"hr_index_part1_l\"><input type=\"text\" id=\"telInput\" placeholder=\"请输入您的电话号码\" /></div>";
        html += "";
        html += "";
        html += "";
        html += "    <div class=\"hr_index_part1_r\" id=\"callBtn\">接通客服</div>";
        html += "";
        html += "";
        html += "";
        html += "    </div>";
        html += "";
        html += "";
        html += "";
        html += "    <div class=\"hr_index_part2\">不方便的时候线上咨询，在线等哦</div>";
        html += "";
        html += "";
        html += "";
        html += "    <!--<a class=\"hr_index_part3\" href=\"http://p6.qiao.baidu.com//im/index?siteid=708511&ucid=467263\" target=\"_blank\">在线客服</a>-->";
        html += "";
        html += "";
        html += "";
        html += "</div>";
        html += "";
        html += "";
        html += "";
        html += "<div class=\"hr_index_light_menu\">";
        html += "";
        html += "";
        html += "";
        html += "	<a href=\"javascript:void(0)\" class=\"hr_index_light_menu_line\"><img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/index_new_p1.png\" /></a>";
        html += "";
        html += "";
        html += "";
        html += "    <!--<a href=\"http://p6.qiao.baidu.com//im/index?siteid=708511&ucid=467263\" target=\"_blank\"><img src=\"http://xinhongru.oss-cn-beijing.aliyuncs.com/images/index_new_p2.png\" /></a>-->";
        html += "";
        html += "";
        html += "";
        html += "</div>";
        html += "";
        html += "";
        html += "";
        html += "<script type=\"text/javascript\">";
        html += "";
        html += "";
        html += "";
        html += "var _py = _py || [];";
        html += "";
        html += "";
        html += "";
        html += "_py.push(['a', '6ss..zrtG6bFPqLMZtZxctr8UEP']);";
        html += "";
        html += "";
        html += "";
        html += "_py.push(['domain','stats.ipinyou.com']);";
        html += "";
        html += "";
        html += "";
        html += "_py.push(['e','']);";
        html += "";
        html += "";
        html += "";
        html += "-function(d) {";
        html += "";
        html += "";
        html += "";
        html += "var s = d.createElement('script'),";
        html += "";
        html += "";
        html += "";
        html += "e = d.body.getElementsByTagName('script')[0]; e.parentNode.insertBefore(s, e),";
        html += "";
        html += "";
        html += "";
        html += "f = 'https:' == location.protocol;";
        html += "";
        html += "";
        html += "";
        html += "s.src = (f ? 'https' : 'http') + '://'+(f?'fm.ipinyou.com':'fm.p0y.cn')+'/j/adv.js';";
        html += "";
        html += "";
        html += "";
        html += "}(document);";
        html += "";
        html += "";
        html += "";
        html += "</script>";
        html += "";
        html += "";
        html += "";
        html += "<noscript>";
        html += "";
        html += "";
        html += "";
        html += "<img src=\"//stats.ipinyou.com/adv.gif?a=6ss..zrtG6bFPqLMZtZxctr8UEP&e=\" style=\"display:none;\"/>";
        html += "";
        html += "";
        html += "";
        html += "</noscript>";
        html += "";
        html += "";
        html += "";
        html += "<script>";
        html += "";
        html += "";
        html += "";
        html += "document.write('<script type=\"text/javascript\"  data-lxb-uid=\"467263\" data-lxb-gid=\"759\" src=\"http://lxbjs.baidu.com/api/asset/api.js?t=' + new Date().getTime() + '\" charset=\"utf-8\"></scr' + 'ipt>' );";
        html += "";
        html += "";
        html += "";
        html += "</script>";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "<script type=\"text/javascript\">";
        html += "";
        html += "";
        html += "";
        html += "var _mvq = _mvq || [];";
        html += "";
        html += "";
        html += "";
        html += "_mvq.push(['$setAccount', 'm-128374-0']);";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "_mvq.push(['$logConversion']);";
        html += "";
        html += "";
        html += "";
        html += "(function() {";
        html += "";
        html += "";
        html += "";
        html += "var mvl = document.createElement('script');";
        html += "";
        html += "";
        html += "";
        html += "mvl.type = 'text/javascript'; mvl.async = true;";
        html += "";
        html += "";
        html += "";
        html += "mvl.src = ('https:' == document.location.protocol ? 'https://static-ssl.mediav.com/mvl.js' : 'http://static.mediav.com/mvl.js');";
        html += "";
        html += "";
        html += "";
        html += "var s = document.getElementsByTagName('script')[0];";
        html += "";
        html += "";
        html += "";
        html += "s.parentNode.insertBefore(mvl, s);";
        html += "";
        html += "";
        html += "";
        html += "})();";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "</script>            ";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "";
        html += "<script>";
        html += "";
        html += "";
        html += "";
        html += "document.getElementById(\"callBtn\").onclick = function () {";
        html += "";
        html += "";
        html += "";
        html += "	lxb.call(document.getElementById(\"telInput\"));";
        html += "";
        html += "";
        html += "";
        html += "};";
        html += "";
        html += "";
        html += "";
        html += "$(\".hr_index_light a\").click(function(){";
        html += "";
        html += "";
        html += "";
        html += "	$(\".hr_index_light\").fadeOut();";
        html += "";
        html += "";
        html += "";
        html += "})";
        html += "";
        html += "";
        html += "";
        html += "$(\".hr_index_light_menu_line\").click(function(){";
        html += "";
        html += "";
        html += "";
        html += "	$(\".hr_index_light\").fadeIn();	";
        html += "";
        html += "";
        html += "";
        html += "})";
        html += "";
        html += "";
        html += "";
        html += "</script>";
        html += "    <script>";
        html += "";
        html += "$.ajax({";
        html += "";
        html += "type: \"POST\",";
        html += "";
        html += "dataType: \"json\",";
        html += "";
        html += "url: '../index.php?a=hit',";
        html += "";
        html += "data: {";
        html += "";
        html += "id:3510,";
        html += "";
        html += "catid:6},";
        html += "";
        html += "success: function (data) {";
        html += "";
        html += "$(\"#hitid\").html(\"浏览：\"+data);";
        html += "";
        html += "}";
        html += "";
        html += "});";
        html += "";
        html += "</script>";
        html += "    <script type=\"text/javascript\">";
        html += "	$(function(){";
        html += "		$(\"div.box>a:first\").attr(\"data-qrcode\",\"http://qcode.hongru.com/qrcode/qrcode.php?content=\"+window.location.href);";
        html += "		$(\"div.box>a\").eq(1).attr(\"data-qrcode\",\"http://qcode.hongru.com/qrcode/qrcode.php?content=\"+window.location.href);	";
        html += "	})";
        html += "	</script>";
        html += "</body>";
        html += "</html>";
        html += "";
        html += "<!-- /Template/default/content/news_details.html -->";

        System.out.println("HTMLDateParse.parseHTMLPublishDate(html) = " + HTMLDateParse.parseHTMLPublishDate(html));
    }
}
